package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CabeceraPedido generated by hbm2java
 */
public class CabeceraPedido implements java.io.Serializable {

	private Integer id;
	private int idCliente;
	private int numPedido;
	private int importeTotal;
	private Set detallePedidos = new HashSet(0);

	public CabeceraPedido() {
	}

	public CabeceraPedido(int idCliente, int numPedido, int importeTotal) {
		this.idCliente = idCliente;
		this.numPedido = numPedido;
		this.importeTotal = importeTotal;
	}

	public CabeceraPedido(int idCliente, int numPedido, int importeTotal, Set detallePedidos) {
		this.idCliente = idCliente;
		this.numPedido = numPedido;
		this.importeTotal = importeTotal;
		this.detallePedidos = detallePedidos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdCliente() {
		return idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public int getNumPedido() {
		return this.numPedido;
	}

	public void setNumPedido(int numPedido) {
		this.numPedido = numPedido;
	}

	public int getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(int importeTotal) {
		this.importeTotal = importeTotal;
	}

	public Set getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
