package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriasMenu generated by hbm2java
 */
public class CategoriasProducto implements java.io.Serializable {

	private Integer id;
	private String categoria;

	public CategoriasProducto() {
	}

	public CategoriasProducto(String categoria) {
		this.categoria = categoria;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}


}
