package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

/**
 * DetallePedido generated by hbm2java
 */
public class DetallePedido implements java.io.Serializable {

	private Integer id;
	private int cabeceraPedido;
	private Productos productos;
	private int cantidad;
	private double totalLinea;

	public DetallePedido() {
	}

	public DetallePedido(int cabeceraPedido, Productos productos, int cantidad, double totalLinea) {
		this.cabeceraPedido = cabeceraPedido;
		this.productos = productos;
		this.cantidad = cantidad;
		this.totalLinea = totalLinea;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCabeceraPedido() {
		return this.cabeceraPedido;
	}

	public void setCabeceraPedido(int cabeceraPedido) {
		this.cabeceraPedido = cabeceraPedido;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public double getTotalLinea() {
		return this.totalLinea;
	}

	public void setTotalLinea(double totalLinea) {
		this.totalLinea = totalLinea;
	}

}
