package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * Mensajeria generated by hbm2java
 */
public class Mensajeria implements java.io.Serializable {

	private Integer id;
	private Personas personas;
	private int idDestinatario;
	private byte[] adjunto;
	private String asunto;
	private String cuerpo;
	private Date fechaEnvio;
	private boolean leido;
	private boolean contestado;

	public Mensajeria() {
	}

	public Mensajeria(Personas personas, int idDestinatario, byte[] adjunto, String asunto, String cuerpo,
			Date fechaEnvio, boolean leido, boolean contestado) {
		this.personas = personas;
		this.idDestinatario = idDestinatario;
		this.adjunto = adjunto;
		this.asunto = asunto;
		this.cuerpo = cuerpo;
		this.fechaEnvio = fechaEnvio;
		this.leido = leido;
		this.contestado = contestado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public int getIdDestinatario() {
		return this.idDestinatario;
	}

	public void setIdDestinatario(int idDestinatario) {
		this.idDestinatario = idDestinatario;
	}

	public byte[] getAdjunto() {
		return this.adjunto;
	}

	public void setAdjunto(byte[] adjunto) {
		this.adjunto = adjunto;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public boolean isLeido() {
		return this.leido;
	}

	public void setLeido(boolean leido) {
		this.leido = leido;
	}

	public boolean isContestado() {
		return this.contestado;
	}

	public void setContestado(boolean contestado) {
		this.contestado = contestado;
	}

}
