package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

/**
 * OpcCategoria generated by hbm2java
 */
public class OpcCategoria implements java.io.Serializable {

	private int id;
	private CategoriasProducto categoriasMenu;
	private String categoria;
	private String opcion;

	public OpcCategoria() {
	}

	public OpcCategoria(int id, CategoriasProducto categoriasMenu, String categoria, String opcion) {
		this.id = id;
		this.categoriasMenu = categoriasMenu;
		this.categoria = categoria;
		this.opcion = opcion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CategoriasProducto getCategoriasMenu() {
		return this.categoriasMenu;
	}

	public void setCategoriasMenu(CategoriasProducto categoriasMenu) {
		this.categoriasMenu = categoriasMenu;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

}
