package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String dni;
	private String pass;
	private String mail;
	private String sexo;
	private byte edad;
	private String tipoPersona;
	private Date fechaAlta;
	private Date fechaBaja;
	private boolean bajaLogica;
	private Set clienteses = new HashSet(0);
	private Set mensajerias = new HashSet(0);
	private Set trabajadoreses = new HashSet(0);

	public Personas() {
	}

	public Personas(String nombre, String apellido1, String apellido2, String dni, String pass, String mail,
			String sexo, byte edad, String tipoPersona, Date fechaAlta, Date fechaBaja, boolean bajaLogica) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.dni = dni;
		this.pass = pass;
		this.mail = mail;
		this.sexo = sexo;
		this.edad = edad;
		this.tipoPersona = tipoPersona;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.bajaLogica = bajaLogica;
	}

	public Personas(String nombre, String apellido1, String apellido2, String dni, String pass, String mail,
			String sexo, byte edad, String tipoPersona, Date fechaAlta, Date fechaBaja, boolean bajaLogica,
			Set clienteses, Set mensajerias, Set trabajadoreses) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.dni = dni;
		this.pass = pass;
		this.mail = mail;
		this.sexo = sexo;
		this.edad = edad;
		this.tipoPersona = tipoPersona;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.bajaLogica = bajaLogica;
		this.clienteses = clienteses;
		this.mensajerias = mensajerias;
		this.trabajadoreses = trabajadoreses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public byte getEdad() {
		return this.edad;
	}

	public void setEdad(byte edad) {
		this.edad = edad;
	}

	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public boolean isBajaLogica() {
		return this.bajaLogica;
	}

	public void setBajaLogica(boolean bajaLogica) {
		this.bajaLogica = bajaLogica;
	}

	public Set getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set clienteses) {
		this.clienteses = clienteses;
	}

	public Set getMensajerias() {
		return this.mensajerias;
	}

	public void setMensajerias(Set mensajerias) {
		this.mensajerias = mensajerias;
	}

	public Set getTrabajadoreses() {
		return this.trabajadoreses;
	}

	public void setTrabajadoreses(Set trabajadoreses) {
		this.trabajadoreses = trabajadoreses;
	}

}
