package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descripcion;
	private int precioUnitarioSinIva;
	private int stock;
	private boolean canjeable;
	private byte descuento;
	private String rutaImagen;
	private boolean borradoLogico;
	private int categoriasProducto;
	private ValoracionesProductos valoracionesProductos;
	private Set detallePedidos = new HashSet(0);

	public Productos() {
	}

	public Productos(String descripcion, int precioUnitarioSinIva, int stock, boolean canjeable, byte descuento,
			String rutaImagen, boolean borradoLogico,int categoriasProducto) {
		this.descripcion = descripcion;
		this.precioUnitarioSinIva = precioUnitarioSinIva;
		this.stock = stock;
		this.canjeable = canjeable;
		this.descuento = descuento;
		this.rutaImagen = rutaImagen;
		this.borradoLogico = borradoLogico;
		this.categoriasProducto = categoriasProducto;
	}

	public Productos(String descripcion, int precioUnitarioSinIva, int stock, boolean canjeable, byte descuento,
			String rutaImagen, boolean borradoLogico,int categoriasProducto, ValoracionesProductos valoracionesProductos, Set detallePedidos) {
		this.descripcion = descripcion;
		this.precioUnitarioSinIva = precioUnitarioSinIva;
		this.stock = stock;
		this.canjeable = canjeable;
		this.descuento = descuento;
		this.rutaImagen = rutaImagen;
		this.borradoLogico = borradoLogico;
		this.categoriasProducto = categoriasProducto;
		this.valoracionesProductos = valoracionesProductos;
		this.detallePedidos = detallePedidos;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getPrecioUnitarioSinIva() {
		return this.precioUnitarioSinIva;
	}

	public void setPrecioUnitarioSinIva(int precioUnitarioSinIva) {
		this.precioUnitarioSinIva = precioUnitarioSinIva;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public boolean isCanjeable() {
		return this.canjeable;
	}

	public void setCanjeable(boolean canjeable) {
		this.canjeable = canjeable;
	}

	public byte getDescuento() {
		return this.descuento;
	}

	public void setDescuento(byte descuento) {
		this.descuento = descuento;
	}

	public String getRutaImagen() {
		return this.rutaImagen;
	}

	public void setRutaImagen(String rutaImagen) {
		this.rutaImagen = rutaImagen;
	}

	public boolean isBorradoLogico() {
		return this.borradoLogico;
	}

	public void setBorradoLogico(boolean borradoLogico) {
		this.borradoLogico = borradoLogico;
	}

	public int getCategoriasProducto() {
		return categoriasProducto;
	}

	public void setCategoriasProducto(int categoriasProducto) {
		this.categoriasProducto = categoriasProducto;
	}
	
	public ValoracionesProductos getValoracionesProductos() {
		return this.valoracionesProductos;
	}

	public void setValoracionesProductos(ValoracionesProductos valoracionesProductos) {
		this.valoracionesProductos = valoracionesProductos;
	}

	public Set getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
