package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

/**
 * Trabajadores generated by hbm2java
 */
public class Trabajadores implements java.io.Serializable {

	private Integer id;
	private Personas personas;
	private String user;
	private double salario;

	public Trabajadores() {
	}

	public Trabajadores(Personas personas, String user, double salario) {
		this.personas = personas;
		this.user = user;
		this.salario = salario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

}
