package model;
// Generated 13-jul-2020 20:30:50 by Hibernate Tools 5.4.12.Final

/**
 * ValoracionesProductos generated by hbm2java
 */
public class ValoracionesProductos implements java.io.Serializable {

	private Integer id;
	private int idProducto;
	private String valoracion;
	private String comentarios;

	public ValoracionesProductos() {
	}
	
	public ValoracionesProductos(int idProducto, String valoracion, String comentarios) {
		this.idProducto = idProducto;
		this.valoracion = valoracion;
		this.comentarios = comentarios;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdProducto() {
		return idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public String getValoracion() {
		return valoracion;
	}

	public void setValoracion(String valoracion) {
		this.valoracion = valoracion;
	}

	public String getComentarios() {
		return comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	

}
